@startuml
'https://plantuml.com/activity-diagram-beta

start

:Set device status to Calibrating;

while (button pressed?) is (false)
  :Wait;
endwhile (true)

:Start timer;
:Start grinding;

while (button pressed?) is (true)
  :Wait;
endwhile (false)

:Stop grinding;
:End timer;

:Save time as grinding time;

:Set device status to Idle;

stop

@enduml
